DominicanBanking/Controllers/PaymentController.cs
using AutoMapper;
using DominicanBanking.Core.Application.DTOS.Account;
using DominicanBanking.Core.Application.Helpers;
using DominicanBanking.Core.Application.Interfaces.Services;
using DominicanBanking.Core.Application.ViewModel.Payment;
using DominicanBanking.Core.Application.ViewModel.Question;
using DominicanBanking.Core.Application.ViewModel.UserProduct;
using DominicanBanking.WebApp.Middlewares;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace DominicanBanking.WebApp.Controllers
{
    [Authorize(Roles = "CLIENT")]
    public class PaymentController : Controller
    {
        private readonly IPaymentServices _paymentServices;
        private readonly IUserProductServices _userProductServices;
        private readonly IUserServices _userServices;
        private readonly IBeneficiaryServices _beneficiaryServices;
        private readonly IMapper _mapper;
        private readonly ValidateUserSession _validateUserSession;

        public PaymentController(IPaymentServices paymentServices, IUserProductServices userProductServices, IUserServices userServices,IBeneficiaryServices beneficiaryServices,IMapper mapper, ValidateUserSession validateUserSession)
        {
            _paymentServices = paymentServices;
            _userProductServices = userProductServices;
            _userServices = userServices;
            _beneficiaryServices = beneficiaryServices;
            _mapper = mapper;
            _validateUserSession = validateUserSession;

        }

        public async Task<IActionResult> Express()
        {
            if (!_validateUserSession.IsLogin())
            {
                return RedirectToRoute(new { action = "Login", controller = "User" });
            }

            var allProduct = await _userProductServices.GetAllViewModelWithIncludes();

            var userLog = HttpContext.Session.Get<AuthenticationResponse>("user");

            ViewBag.Account = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Available: ${x.Amount}" }), "Value", "Text");

            return View(new SavePaymentViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Express(SavePaymentViewModel model) {

            var allProduct = await _userProductServices.GetAllViewModelWithIncludes();
            var userLog = HttpContext.Session.Get<AuthenticationResponse>("user");
            if (!ModelState.IsValid)
            {

                ViewBag.Account = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} | Available: ${x.Amount}" }), "Value", "Text");

                return View(model);
            }
            if (model.IdentifyNumberFrom == model.IdentifyNumberTo)
            {
                ModelState.AddModelError("IdentifyNumberTo", "The account number is the same, please write another account");
                ViewBag.Account = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Available: ${x.Amount}" }), "Value", "Text");

                return View(model);
            }

            var AccountFrom = allProduct.FirstOrDefault(r => r.IdentifyNumber == model.IdentifyNumberFrom);
            var AccountTo = allProduct.FirstOrDefault(r => r.IdentifyNumber == model.IdentifyNumberTo);

            if (AccountTo == null
                || AccountTo.ProductId == 2
                || AccountTo.ProductId == 3)
            {
                ModelState.AddModelError("IdentifyNumberTo", "The account number doesn't exist or This account number is an Loan or Credit Card from another person.");
                ViewBag.Account = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Available: ${x.Amount}" }), "Value", "Text");

                return View(model);
            }


            if (model.Amount>AccountFrom.Amount)
            {
                ModelState.AddModelError("Amount", "The Amount is greater than your have in that account.");
                ViewBag.Account = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Available: ${x.Amount}" }), "Value", "Text");

                return View(model);
            }

            var user = await _userServices.GetAllUserAsync();
            model.TypeId = 1;

            return View("QuestionExpress",new QuestionViewModel() {
                FullName=$"{user.FirstOrDefault(user => user.Id == AccountTo.UserId).FirstName} {user.FirstOrDefault(user => user.Id == AccountTo.UserId).LastName}",
                IdentifyNumberTo = model.IdentifyNumberTo,
                IdentifyNumberFrom = model.IdentifyNumberFrom,
                Amount = model.Amount,
                TypeId = model.TypeId,
                UserId = AccountFrom.UserId});
        }

        [HttpPost]
        public async Task<IActionResult> QuestionExpress(QuestionViewModel model) {

            var allProduct = await _userProductServices.GetAllViewModelWithIncludes();
            var AccountFrom = allProduct.FirstOrDefault(r => r.IdentifyNumber == model.IdentifyNumberFrom);
            var AccountTo = allProduct.FirstOrDefault(r => r.IdentifyNumber == model.IdentifyNumberTo);

            AccountFrom.Amount -= model.Amount;
            AccountTo.Amount += model.Amount;

            var SaveFrom = _mapper.Map<SaveUserProductViewModel>(AccountFrom);

            var SaveTo = _mapper.Map<SaveUserProductViewModel>(AccountTo);

            var payment = _mapper.Map<SavePaymentViewModel>(model);

            await _userProductServices.Update(SaveFrom,AccountFrom.Id);
            await _userProductServices.Update(SaveTo, AccountTo.Id);
            await _paymentServices.Add(payment);


            return RedirectToRoute(new {action="Client",controller="Home" });
        
        }

        public async Task<IActionResult> CreditCard()
        {
            if (!_validateUserSession.IsLogin())
            {
                return RedirectToRoute(new { action = "Login", controller = "User" });
            }

            var allProduct = await _userProductServices.GetAllViewModelWithIncludes();

            var userLog = HttpContext.Session.Get<AuthenticationResponse>("user");

            ViewBag.Account = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Available: ${x.Amount}" }), "Value", "Text");
            ViewBag.CreditCard = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 2).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Dues: ${x.Amount}" }), "Value", "Text");

            return View(new SavePaymentViewModel());
        }


        [HttpPost]
        public async Task<IActionResult> CreditCard(SavePaymentViewModel model) {

            var userLog = HttpContext.Session.Get<AuthenticationResponse>("user");
            var allProduct = await _userProductServices.GetAllViewModelWithIncludes();

            if (!ModelState.IsValid)
            {

                ViewBag.Account = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Available: ${x.Amount}" }), "Value", "Text");
                ViewBag.CreditCard = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 2).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Dues: ${x.Amount}" }), "Value", "Text");

                return View(model);
            }
            var CreditCard = allProduct.FirstOrDefault(x=>x.IdentifyNumber == model.IdentifyNumberTo);
            var Account = allProduct.FirstOrDefault(x=>x.IdentifyNumber == model.IdentifyNumberFrom);

            if (CreditCard.Amount == 0) {

                ViewBag.Account = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Available: ${x.Amount}" }), "Value", "Text");
                ViewBag.CreditCard = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 2).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Dues: ${x.Amount}" }), "Value", "Text");

                ModelState.AddModelError("IdentifyNumberTo", "This credit card hasn't debts. Select another oner");
                return View(model);
            }

            if (model.Amount>Account.Amount)
            {

                ViewBag.Account = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Available: ${x.Amount}" }), "Value", "Text");
                ViewBag.CreditCard = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 2).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} - Dues: ${x.Amount}" }), "Value", "Text");

                ModelState.AddModelError("Amount", "The Amount is greater than your have in that account.");
                return View(model);
            }

            if (model.Amount>CreditCard.Amount)
            {
                Account.Amount -= model.Amount;
                CreditCard.Amount = model.Amount -= CreditCard.Amount;
                Account.Amount += CreditCard.Amount;
                CreditCard.Amount -=CreditCard.Amount;

DominicanBanking/Controllers/TransferController.cs
using DominicanBanking.Core.Application.DTOS.Account;
using DominicanBanking.Core.Application.Helpers;
using DominicanBanking.Core.Application.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DominicanBanking.WebApp.Middlewares;
using DominicanBanking.Core.Application.ViewModel.Transfer;
using DominicanBanking.Core.Application.ViewModel.UserProduct;

namespace DominicanBanking.WebApp.Controllers
{
    [Authorize(Roles="CLIENT")]
    public class TransferController : Controller
    {
        private readonly ITransferServices _transferServices;
        private readonly IUserProductServices _userProductServices;
        private readonly IMapper _mapper;
        private readonly ValidateUserSession _validateUserSession;

        public TransferController(IUserProductServices userProductServices,ITransferServices transferServices,IMapper mapper, ValidateUserSession validateUserSession)
        {
            _userProductServices = userProductServices;
            _transferServices = transferServices;
            _mapper = mapper;
            _validateUserSession = validateUserSession;
        }
        public async Task<IActionResult> Create()
        {
            if (!_validateUserSession.IsLogin())
            {
                return RedirectToRoute(new { action = "Login", controller = "User" });
            }
            var userLog = HttpContext.Session.Get<AuthenticationResponse>("user");
            var allProduct = await _userProductServices.GetAllViewModelWithIncludes();

            ViewBag.AccountFrom = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} | Avalaible: ${x.Amount}" }), "Value", "Text");
            ViewBag.AccountTo = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} | {x.ProductName}" }), "Value", "Text");

            return View(new SaveTransferViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(SaveTransferViewModel model) {

            var userLog = HttpContext.Session.Get<AuthenticationResponse>("user");
            var allProduct = await _userProductServices.GetAllViewModelWithIncludes();

            if (!ModelState.IsValid)
            {
                ViewBag.AccountFrom = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} | Avalaible: ${x.Amount}" }), "Value", "Text");
                ViewBag.AccountTo = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} | {x.ProductName}" }), "Value", "Text");

                return View(model);
            }

            var AccountFrom = allProduct.FirstOrDefault(up => up.IdentifyNumber == model.IdentifyNumberFrom);
            var AccountTo = allProduct.FirstOrDefault(up => up.IdentifyNumber == model.IdentifyNumberTo);

            if (AccountFrom.IdentifyNumber == AccountTo.IdentifyNumber)
            {
                ViewBag.AccountFrom = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} | Avalaible: ${x.Amount}" }), "Value", "Text");
                ViewBag.AccountTo = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} | {x.ProductName}" }), "Value", "Text");

                return View(model);
            }

            if (model.Amount>AccountFrom.Amount)
            {
                ViewBag.AccountFrom = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} | Avalaible: ${x.Amount}" }), "Value", "Text");
                ViewBag.AccountTo = new SelectList(allProduct.Where(x => x.UserId == userLog.Id && x.ProductId == 1).Select(x => new { Value = x.IdentifyNumber, Text = $"{x.IdentifyNumber} | {x.ProductName}" }), "Value", "Text");
                ModelState.AddModelError("Amount", "The Amount is greater than you have in that account");

                return View(model);
            }

            AccountFrom.Amount -= model.Amount;
            AccountTo.Amount += model.Amount;


            model.UserId = userLog.Id;

            await _userProductServices.Update(_mapper.Map<SaveUserProductViewModel>(AccountFrom), AccountFrom.Id);
            await _userProductServices.Update(_mapper.Map<SaveUserProductViewModel>(AccountTo), AccountTo.Id);

            await _transferServices.Add(model);

            return RedirectToRoute(new { action="Client",controller="Home"});
        
        }
    }
}

DominicanBanking/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using DominicanBanking.Core.Application.Helpers
@using DominicanBanking.Core.Application.DTOS.Account
@inject IHttpContextAccessor httpContextAccessor
@{var User = httpContextAccessor.HttpContext.Session.Get<AuthenticationResponse>("user");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DominicanBanking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/cdb.min.css"/>
</head>
<body>
    @if (User != null)
    {
        <div class="container_Home">
                                        @{var isAdmin = User.Roles.Any(r => r == "ADMINISTRATOR");}
            <nav class="navbar navbar-expand-lg navbar-light bg-primary text-white">
                <div class="container-fluid">
                    <a class="nav_item1" asp-action="@(isAdmin?"DashBoard":"Client")" asp-controller="Home"><i class="fa fa-building-columns fa-sm" aria-hidden="true"></i> Banking </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            @if(isAdmin){
                            <li class="nav-item dropdown">
                                <a class="nav_item dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-user fa-sm me-2"></i>User Manager
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-action="UserList" asp-controller="User">User List</a></li>
                                    <li><a class="dropdown-item" asp-action="Register" asp-controller="User">Create</a></li>
                                    <li><a class="dropdown-item" asp-action="Create" asp-controller="UserProduct">Add Product</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav_item dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-user fa-sm me-2"></i>User Product
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-action="Index" asp-controller="UserProduct">List</a></li>
                                    <li><a class="dropdown-item" asp-action="Create" asp-controller="UserProduct">Create</a></li>
                                </ul>
                            </li>
                            }
                            else{
                            <li class="nav-item dropdown">
                                <a class="nav_item dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-money-bill fa-sm me-2"></i>Payments
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-action="Express" asp-controller="Payment">Express Payment</a></li>
                                    <li><a class="dropdown-item" asp-action="CreditCard" asp-controller="Payment">Credit Card Payment</a></li>
                                    <li><a class="dropdown-item" asp-action="Loan" asp-controller="Payment">Loan Payment</a></li>
                                    <li><a class="dropdown-item" asp-action="Beneficiary" asp-controller="Payment">Beneficiary Payment</a></li>
                                </ul>
                            </li>
                            <li class="nav-item ms-2">
                                <a class="nav_item" asp-action="Index" asp-controller="Beneficiary">
                                 <i class="fas fa-piggy-bank fa-sm ms-1"></i>
                                 Beneficiary
                                 </a>
                            </li>
                            <li class="nav-item ms-3">
                                <a class="nav_item" asp-action="New" asp-controller="CashAdvance">
                                 <i class="fab fa-cc-visa fa-sm ms-1"></i>
                                 Cash Advances
                                 </a>
                            </li>
                             <li class="nav-item ms-3">
                                <a class="nav_item" asp-action="Create" asp-controller="Transfer">
                                 <i class="fas fa-arrow-right-arrow-left fa-sm ms-1"></i>
                                 Transfer
                                 </a>
                            </li>

                            }
                        </ul>
                        <ul class="navbar-nav">

                            <li class="nav-item dropdown">
                                <a class="nav_item dropdown-toggle me-3" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-power-off fa-sm me-2" aria-hidden="true"></i>@User.FirstName @User.LastName
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-action="LogOut" asp-controller="User">Logout</a></li>

                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        }
    <div class="containerr">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - DominicanBanking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/cdb.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>